---
#-----------------------------------------------------------------
# INSIGHT - Observability Workbench
#-----------------------------------------------------------------
insight_enabled: true             # enable insight workbench?
workbench_port: 8080              # workbench listen port
workbench_dir: /data/workbench    # workbench deployment directory
workbench_user: "{{ node_user | default('root') }}"
workbench_group: "{{ node_user | default('root') }}"

# nodejs version and registry
nodejs_version: 20
nodejs_registry: https://registry.npmmirror.com

# build options
workbench_clean: false            # clean workbench directory before deployment?
workbench_build: true             # run npm install & build during setup?
